version: '3.8'

services:
  # Base de données PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: moneymirror-postgres
    environment:
      POSTGRES_DB: moneymirror
      POSTGRES_USER: moneymirror
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U moneymirror"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Application Next.js (développement)
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: moneymirror-app
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://moneymirror:password@postgres:5432/moneymirror?schema=public"
      NEXTAUTH_URL: "http://localhost:3000"
      NEXTAUTH_SECRET: "your-dev-secret-key"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      postgres:
        condition: service_healthy
    command: sh -c "npx prisma db push && npm run dev"

volumes:
  postgres_data: